<?php

return [
    'seed_count' => 60,
    'modules' => [
        'proiecte' => [
            'label' => 'Proiecte',
            'icon' => 'fa-diagram-project',
            'route_prefix' => 'proiecte',
            'table_prefix' => 'prj_',
            'entities' => [
                'proiecte' => [
                    'label' => 'Proiecte',
                    'icon' => 'fa-folder-open',
                    'table' => 'prj_proiecte',
                    'columns' => [
                        ['name' => 'cod_proiect', 'label' => 'Cod proiect', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_proiect', 'label' => 'Denumire proiect', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_proiect', 'label' => 'Tip proiect', 'type' => 'select', 'required' => true, 'options' => ['Scule motorizate', 'Echipamente agricole', 'Piese auto', 'Service tehnic']],
                        ['name' => 'status_proiect', 'label' => 'Status proiect', 'type' => 'select', 'required' => true, 'options' => ['Propus', 'In derulare', 'Finalizat', 'Suspendat']],
                        ['name' => 'buget_aprobat', 'label' => 'Buget aprobat', 'type' => 'decimal', 'required' => true],
                        ['name' => 'marja_estimata', 'label' => 'Marja estimata (%)', 'type' => 'decimal'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'faze' => [
                    'label' => 'Faze Proiect',
                    'icon' => 'fa-layer-group',
                    'table' => 'prj_faze_proiect',
                    'columns' => [
                        ['name' => 'proiect_id', 'label' => 'ID proiect', 'type' => 'bigint', 'required' => true, 'reference_table' => 'prj_proiecte'],
                        ['name' => 'cod_faza', 'label' => 'Cod faza', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_faza', 'label' => 'Denumire faza', 'type' => 'string', 'required' => true],
                        ['name' => 'responsabil', 'label' => 'Responsabil', 'type' => 'string', 'required' => true],
                        ['name' => 'status_faza', 'label' => 'Status faza', 'type' => 'select', 'required' => true, 'options' => ['Planificata', 'In executie', 'Finalizata', 'Suspendata']],
                        ['name' => 'procent_realizare', 'label' => 'Procent realizare (%)', 'type' => 'decimal', 'required' => true],
                        ['name' => 'cost_planificat', 'label' => 'Cost planificat', 'type' => 'decimal'],
                    ],
                ],
                'activitati' => [
                    'label' => 'Activitati pe Faze',
                    'icon' => 'fa-list-check',
                    'table' => 'prj_activitati_faze',
                    'columns' => [
                        ['name' => 'faza_id', 'label' => 'ID faza', 'type' => 'bigint', 'required' => true, 'reference_table' => 'prj_faze_proiect'],
                        ['name' => 'cod_activitate', 'label' => 'Cod activitate', 'type' => 'string', 'required' => true],
                        ['name' => 'descriere_activitate', 'label' => 'Descriere activitate', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_activitate', 'label' => 'Tip activitate', 'type' => 'select', 'required' => true, 'options' => ['Montaj', 'Testare', 'Aprovizionare', 'Livrare', 'Service']],
                        ['name' => 'ore_planificate', 'label' => 'Ore planificate', 'type' => 'decimal', 'required' => true],
                        ['name' => 'cost_activitate', 'label' => 'Cost activitate', 'type' => 'decimal'],
                        ['name' => 'status_activitate', 'label' => 'Status activitate', 'type' => 'select', 'required' => true, 'options' => ['Planificata', 'Executata', 'Blocata']],
                    ],
                ],
                'alocari-resurse' => [
                    'label' => 'Alocare Resurse',
                    'icon' => 'fa-people-group',
                    'table' => 'prj_alocari_resurse',
                    'columns' => [
                        ['name' => 'proiect_id', 'label' => 'ID proiect', 'type' => 'bigint', 'required' => true, 'reference_table' => 'prj_proiecte'],
                        ['name' => 'denumire_resursa', 'label' => 'Denumire resursa', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_resursa', 'label' => 'Tip resursa', 'type' => 'select', 'required' => true, 'options' => ['Personal', 'Utilaj', 'Vehicul', 'Consumabil']],
                        ['name' => 'cantitate_alocata', 'label' => 'Cantitate alocata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'cost_unitar', 'label' => 'Cost unitar', 'type' => 'decimal', 'required' => true],
                        ['name' => 'cost_total', 'label' => 'Cost total', 'type' => 'decimal'],
                        ['name' => 'status_alocare', 'label' => 'Status alocare', 'type' => 'select', 'required' => true, 'options' => ['Activa', 'In asteptare', 'Finalizata']],
                    ],
                ],
                'consumuri' => [
                    'label' => 'Consumuri',
                    'icon' => 'fa-oil-can',
                    'table' => 'prj_consumuri',
                    'columns' => [
                        ['name' => 'proiect_id', 'label' => 'ID proiect', 'type' => 'bigint', 'required' => true, 'reference_table' => 'prj_proiecte'],
                        ['name' => 'articol_consum', 'label' => 'Articol consum', 'type' => 'string', 'required' => true],
                        ['name' => 'categorie_consum', 'label' => 'Categorie consum', 'type' => 'select', 'required' => true, 'options' => ['Combustibil', 'Piese', 'Lubrifianti', 'Accesorii']],
                        ['name' => 'cantitate_consumata', 'label' => 'Cantitate consumata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'cost_unitar', 'label' => 'Cost unitar', 'type' => 'decimal', 'required' => true],
                        ['name' => 'cost_total', 'label' => 'Cost total', 'type' => 'decimal'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'costuri' => [
                    'label' => 'Costuri',
                    'icon' => 'fa-money-bill-wave',
                    'table' => 'prj_costuri',
                    'columns' => [
                        ['name' => 'proiect_id', 'label' => 'ID proiect', 'type' => 'bigint', 'required' => true, 'reference_table' => 'prj_proiecte'],
                        ['name' => 'tip_cost', 'label' => 'Tip cost', 'type' => 'select', 'required' => true, 'options' => ['Materiale', 'Manopera', 'Logistica', 'Subcontractare']],
                        ['name' => 'descriere_cost', 'label' => 'Descriere cost', 'type' => 'string', 'required' => true],
                        ['name' => 'valoare_cost', 'label' => 'Valoare cost', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_cost', 'label' => 'Status cost', 'type' => 'select', 'required' => true, 'options' => ['Bugetat', 'Aprobat', 'Platit']],
                        ['name' => 'centru_cost', 'label' => 'Centru cost', 'type' => 'string', 'required' => true],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'grade-realizare' => [
                    'label' => 'Grade de Realizare',
                    'icon' => 'fa-gauge-high',
                    'table' => 'prj_grade_realizare',
                    'columns' => [
                        ['name' => 'proiect_id', 'label' => 'ID proiect', 'type' => 'bigint', 'required' => true, 'reference_table' => 'prj_proiecte'],
                        ['name' => 'indicator', 'label' => 'Indicator', 'type' => 'string', 'required' => true],
                        ['name' => 'valoare_tinta', 'label' => 'Valoare tinta', 'type' => 'decimal', 'required' => true],
                        ['name' => 'valoare_curenta', 'label' => 'Valoare curenta', 'type' => 'decimal', 'required' => true],
                        ['name' => 'procent_realizare', 'label' => 'Procent realizare (%)', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_indicator', 'label' => 'Status indicator', 'type' => 'select', 'required' => true, 'options' => ['Sub tinta', 'In tinta', 'Peste tinta']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'cashflow' => [
                    'label' => 'Cashflow Proiecte',
                    'icon' => 'fa-sack-dollar',
                    'table' => 'prj_cashflow',
                    'columns' => [
                        ['name' => 'proiect_id', 'label' => 'ID proiect', 'type' => 'bigint', 'required' => true, 'reference_table' => 'prj_proiecte'],
                        ['name' => 'sursa_flux', 'label' => 'Sursa flux', 'type' => 'select', 'required' => true, 'options' => ['Avans client', 'Factura emisa', 'Incasare', 'Plata furnizor']],
                        ['name' => 'suma_flux', 'label' => 'Suma flux', 'type' => 'decimal', 'required' => true],
                        ['name' => 'tip_flux', 'label' => 'Tip flux', 'type' => 'select', 'required' => true, 'options' => ['Intrare', 'Iesire']],
                        ['name' => 'sold_dupa_operatie', 'label' => 'Sold dupa operatie', 'type' => 'decimal'],
                        ['name' => 'referinta_document', 'label' => 'Referinta document', 'type' => 'string'],
                        ['name' => 'status_flux', 'label' => 'Status flux', 'type' => 'select', 'required' => true, 'options' => ['Planificat', 'Confirmat', 'Anulat']],
                    ],
                ],
                'profitabilitate' => [
                    'label' => 'Profitabilitate',
                    'icon' => 'fa-chart-line',
                    'table' => 'prj_profitabilitate',
                    'columns' => [
                        ['name' => 'proiect_id', 'label' => 'ID proiect', 'type' => 'bigint', 'required' => true, 'reference_table' => 'prj_proiecte'],
                        ['name' => 'venit_total', 'label' => 'Venit total', 'type' => 'decimal', 'required' => true],
                        ['name' => 'cost_total', 'label' => 'Cost total', 'type' => 'decimal', 'required' => true],
                        ['name' => 'profit_brut', 'label' => 'Profit brut', 'type' => 'decimal'],
                        ['name' => 'marja_profit', 'label' => 'Marja profit (%)', 'type' => 'decimal'],
                        ['name' => 'nivel_profitabilitate', 'label' => 'Nivel profitabilitate', 'type' => 'select', 'required' => true, 'options' => ['Scazuta', 'Medie', 'Ridicata']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
            ],
        ],
        'contracte' => [
            'label' => 'Contracte Client',
            'icon' => 'fa-file-signature',
            'route_prefix' => 'contracte-client',
            'table_prefix' => 'ctc_',
            'entities' => [
                'clienti' => [
                    'label' => 'Clienti',
                    'icon' => 'fa-building-user',
                    'table' => 'ctc_clienti',
                    'columns' => [
                        ['name' => 'cod_client', 'label' => 'Cod client', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_client', 'label' => 'Denumire client', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_client', 'label' => 'Tip client', 'type' => 'select', 'required' => true, 'options' => ['Distribuitor', 'Retail', 'Service auto', 'Ferma agricola']],
                        ['name' => 'persoana_contact', 'label' => 'Persoana contact', 'type' => 'string', 'required' => true],
                        ['name' => 'telefon', 'label' => 'Telefon', 'type' => 'string', 'required' => true],
                        ['name' => 'localitate', 'label' => 'Localitate', 'type' => 'string', 'required' => true],
                        ['name' => 'status_client', 'label' => 'Status client', 'type' => 'select', 'required' => true, 'options' => ['Activ', 'In analiza', 'Suspendat']],
                    ],
                ],
                'oferte' => [
                    'label' => 'Oferte',
                    'icon' => 'fa-file-circle-plus',
                    'table' => 'ctc_oferte',
                    'columns' => [
                        ['name' => 'client_id', 'label' => 'ID client', 'type' => 'bigint', 'required' => true, 'reference_table' => 'ctc_clienti'],
                        ['name' => 'cod_oferta', 'label' => 'Cod oferta', 'type' => 'string', 'required' => true],
                        ['name' => 'descriere_oferta', 'label' => 'Descriere oferta', 'type' => 'string', 'required' => true],
                        ['name' => 'status_oferta', 'label' => 'Status oferta', 'type' => 'select', 'required' => true, 'options' => ['In lucru', 'Transmisa', 'Acceptata', 'Respinsa']],
                        ['name' => 'valoare_totala', 'label' => 'Valoare totala', 'type' => 'decimal', 'required' => true],
                        ['name' => 'discount_ofertat', 'label' => 'Discount ofertat (%)', 'type' => 'decimal'],
                        ['name' => 'moneda', 'label' => 'Moneda', 'type' => 'select', 'required' => true, 'options' => ['RON', 'EUR', 'USD']],
                    ],
                ],
                'contracte' => [
                    'label' => 'Contracte',
                    'icon' => 'fa-file-contract',
                    'table' => 'ctc_contracte',
                    'columns' => [
                        ['name' => 'client_id', 'label' => 'ID client', 'type' => 'bigint', 'required' => true, 'reference_table' => 'ctc_clienti'],
                        ['name' => 'oferta_id', 'label' => 'ID oferta', 'type' => 'bigint', 'reference_table' => 'ctc_oferte'],
                        ['name' => 'cod_contract', 'label' => 'Cod contract', 'type' => 'string', 'required' => true],
                        ['name' => 'obiect_contract', 'label' => 'Obiect contract', 'type' => 'string', 'required' => true],
                        ['name' => 'status_contract', 'label' => 'Status contract', 'type' => 'select', 'required' => true, 'options' => ['Activ', 'In executie', 'Finalizat', 'Reziliat']],
                        ['name' => 'valoare_contract', 'label' => 'Valoare contract', 'type' => 'decimal', 'required' => true],
                        ['name' => 'moneda', 'label' => 'Moneda', 'type' => 'select', 'required' => true, 'options' => ['RON', 'EUR', 'USD']],
                    ],
                ],
                'linii-contract' => [
                    'label' => 'Linii Contract',
                    'icon' => 'fa-list-ul',
                    'table' => 'ctc_linii_contracte',
                    'columns' => [
                        ['name' => 'contract_id', 'label' => 'ID contract', 'type' => 'bigint', 'required' => true, 'reference_table' => 'ctc_contracte'],
                        ['name' => 'cod_produs', 'label' => 'Cod produs', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_produs', 'label' => 'Denumire produs', 'type' => 'string', 'required' => true],
                        ['name' => 'cantitate', 'label' => 'Cantitate', 'type' => 'decimal', 'required' => true],
                        ['name' => 'pret_unitar', 'label' => 'Pret unitar', 'type' => 'decimal', 'required' => true],
                        ['name' => 'valoare_linie', 'label' => 'Valoare linie', 'type' => 'decimal'],
                        ['name' => 'categorie_produs', 'label' => 'Categorie produs', 'type' => 'select', 'required' => true, 'options' => ['Scule motorizate', 'Echipamente agricole', 'Piese auto']],
                    ],
                ],
                'esalonari-plata' => [
                    'label' => 'Esalonari de Plata',
                    'icon' => 'fa-calendar-check',
                    'table' => 'ctc_esalonari_plata',
                    'columns' => [
                        ['name' => 'contract_id', 'label' => 'ID contract', 'type' => 'bigint', 'required' => true, 'reference_table' => 'ctc_contracte'],
                        ['name' => 'denumire_transa', 'label' => 'Denumire transa', 'type' => 'string', 'required' => true],
                        ['name' => 'procent_transa', 'label' => 'Procent transa (%)', 'type' => 'decimal', 'required' => true],
                        ['name' => 'suma_transa', 'label' => 'Suma transa', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_transa', 'label' => 'Status transa', 'type' => 'select', 'required' => true, 'options' => ['Programata', 'Facturata', 'Incasata']],
                        ['name' => 'termen_plata', 'label' => 'Termen plata', 'type' => 'string', 'required' => true],
                        ['name' => 'modalitate_plata', 'label' => 'Modalitate plata', 'type' => 'select', 'required' => true, 'options' => ['Transfer bancar', 'Card', 'Numerar']],
                    ],
                ],
                'facturi' => [
                    'label' => 'Facturi',
                    'icon' => 'fa-file-invoice-dollar',
                    'table' => 'ctc_facturi',
                    'invoice_pdf' => true,
                    'columns' => [
                        ['name' => 'client_id', 'label' => 'ID client', 'type' => 'bigint', 'required' => true, 'reference_table' => 'ctc_clienti'],
                        ['name' => 'contract_id', 'label' => 'ID contract', 'type' => 'bigint', 'reference_table' => 'ctc_contracte'],
                        ['name' => 'cod_factura', 'label' => 'Cod factura', 'type' => 'string', 'required' => true],
                        ['name' => 'status_factura', 'label' => 'Status factura', 'type' => 'select', 'required' => true, 'options' => ['Emisa', 'Partiala', 'Incasata', 'Restanta']],
                        ['name' => 'valoare_totala', 'label' => 'Valoare totala', 'type' => 'decimal', 'required' => true],
                        ['name' => 'moneda', 'label' => 'Moneda', 'type' => 'select', 'required' => true, 'options' => ['RON', 'EUR', 'USD']],
                        ['name' => 'sold_factura', 'label' => 'Sold factura', 'type' => 'decimal'],
                    ],
                ],
                'pozitii-factura' => [
                    'label' => 'Pozitii Factura',
                    'icon' => 'fa-receipt',
                    'table' => 'ctc_pozitii_factura',
                    'columns' => [
                        ['name' => 'factura_id', 'label' => 'ID factura', 'type' => 'bigint', 'required' => true, 'reference_table' => 'ctc_facturi'],
                        ['name' => 'cod_articol', 'label' => 'Cod articol', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_articol', 'label' => 'Denumire articol', 'type' => 'string', 'required' => true],
                        ['name' => 'cantitate', 'label' => 'Cantitate', 'type' => 'decimal', 'required' => true],
                        ['name' => 'pret_unitar', 'label' => 'Pret unitar', 'type' => 'decimal', 'required' => true],
                        ['name' => 'valoare_linie', 'label' => 'Valoare linie', 'type' => 'decimal'],
                        ['name' => 'tip_articol', 'label' => 'Tip articol', 'type' => 'select', 'required' => true, 'options' => ['Scule motorizate', 'Echipamente agricole', 'Piese auto']],
                    ],
                ],
                'incasari' => [
                    'label' => 'Incasari',
                    'icon' => 'fa-cash-register',
                    'table' => 'ctc_incasari',
                    'columns' => [
                        ['name' => 'factura_id', 'label' => 'ID factura', 'type' => 'bigint', 'required' => true, 'reference_table' => 'ctc_facturi'],
                        ['name' => 'cod_incasare', 'label' => 'Cod incasare', 'type' => 'string', 'required' => true],
                        ['name' => 'suma_incasata', 'label' => 'Suma incasata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'modalitate_incasare', 'label' => 'Modalitate incasare', 'type' => 'select', 'required' => true, 'options' => ['Transfer bancar', 'Card', 'Numerar']],
                        ['name' => 'status_incasare', 'label' => 'Status incasare', 'type' => 'select', 'required' => true, 'options' => ['Confirmata', 'In procesare', 'Respinsa']],
                        ['name' => 'referinta_document', 'label' => 'Referinta document', 'type' => 'string'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'conditii-comerciale' => [
                    'label' => 'Conditii Comerciale',
                    'icon' => 'fa-handshake',
                    'table' => 'ctc_conditii_comerciale',
                    'columns' => [
                        ['name' => 'client_id', 'label' => 'ID client', 'type' => 'bigint', 'required' => true, 'reference_table' => 'ctc_clienti'],
                        ['name' => 'termen_livrare', 'label' => 'Termen livrare', 'type' => 'string', 'required' => true],
                        ['name' => 'termen_plata', 'label' => 'Termen plata', 'type' => 'string', 'required' => true],
                        ['name' => 'discount_comercial', 'label' => 'Discount comercial (%)', 'type' => 'decimal'],
                        ['name' => 'garantie_luni', 'label' => 'Garantie (luni)', 'type' => 'integer'],
                        ['name' => 'limita_credit', 'label' => 'Limita credit', 'type' => 'decimal'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
            ],
        ],
        'aprovizionare' => [
            'label' => 'Aprovizionare',
            'icon' => 'fa-truck-ramp-box',
            'route_prefix' => 'aprovizionare',
            'table_prefix' => 'apr_',
            'entities' => [
                'furnizori' => [
                    'label' => 'Furnizori',
                    'icon' => 'fa-warehouse',
                    'table' => 'apr_furnizori',
                    'columns' => [
                        ['name' => 'cod_furnizor', 'label' => 'Cod furnizor', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_furnizor', 'label' => 'Denumire furnizor', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_furnizor', 'label' => 'Tip furnizor', 'type' => 'select', 'required' => true, 'options' => ['Importator', 'Distributor local', 'Producator', 'Service piese']],
                        ['name' => 'persoana_contact', 'label' => 'Persoana contact', 'type' => 'string', 'required' => true],
                        ['name' => 'telefon', 'label' => 'Telefon', 'type' => 'string', 'required' => true],
                        ['name' => 'localitate', 'label' => 'Localitate', 'type' => 'string', 'required' => true],
                        ['name' => 'status_furnizor', 'label' => 'Status furnizor', 'type' => 'select', 'required' => true, 'options' => ['Activ', 'Preferat', 'Suspendat']],
                    ],
                ],
                'necesare' => [
                    'label' => 'Necesare Aprovizionare',
                    'icon' => 'fa-clipboard-list',
                    'table' => 'apr_necesare',
                    'columns' => [
                        ['name' => 'cod_necesar', 'label' => 'Cod necesar', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_articol', 'label' => 'Denumire articol', 'type' => 'string', 'required' => true],
                        ['name' => 'categorie_articol', 'label' => 'Categorie articol', 'type' => 'select', 'required' => true, 'options' => ['Scule motorizate', 'Echipamente agricole', 'Piese auto', 'Consumabile']],
                        ['name' => 'cantitate_necesara', 'label' => 'Cantitate necesara', 'type' => 'decimal', 'required' => true],
                        ['name' => 'prioritate', 'label' => 'Prioritate', 'type' => 'select', 'required' => true, 'options' => ['Scazuta', 'Medie', 'Ridicata', 'Critica']],
                        ['name' => 'status_necesar', 'label' => 'Status necesar', 'type' => 'select', 'required' => true, 'options' => ['Deschis', 'Aprobat', 'Inchis']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'cereri' => [
                    'label' => 'Cereri Aprovizionare',
                    'icon' => 'fa-file-pen',
                    'table' => 'apr_cereri',
                    'columns' => [
                        ['name' => 'furnizor_id', 'label' => 'ID furnizor', 'type' => 'bigint', 'reference_table' => 'apr_furnizori'],
                        ['name' => 'cod_cerere', 'label' => 'Cod cerere', 'type' => 'string', 'required' => true],
                        ['name' => 'articol', 'label' => 'Articol', 'type' => 'string', 'required' => true],
                        ['name' => 'cantitate_ceruta', 'label' => 'Cantitate ceruta', 'type' => 'decimal', 'required' => true],
                        ['name' => 'pret_estimat', 'label' => 'Pret estimat', 'type' => 'decimal'],
                        ['name' => 'status_cerere', 'label' => 'Status cerere', 'type' => 'select', 'required' => true, 'options' => ['Initiata', 'Trimisa', 'Acceptata', 'Respinsa']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'comenzi' => [
                    'label' => 'Comenzi Furnizor',
                    'icon' => 'fa-cart-plus',
                    'table' => 'apr_comenzi',
                    'columns' => [
                        ['name' => 'furnizor_id', 'label' => 'ID furnizor', 'type' => 'bigint', 'required' => true, 'reference_table' => 'apr_furnizori'],
                        ['name' => 'cod_comanda', 'label' => 'Cod comanda', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_comanda', 'label' => 'Tip comanda', 'type' => 'select', 'required' => true, 'options' => ['Scule motorizate', 'Echipamente agricole', 'Piese auto']],
                        ['name' => 'valoare_comanda', 'label' => 'Valoare comanda', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_comanda', 'label' => 'Status comanda', 'type' => 'select', 'required' => true, 'options' => ['Lansata', 'Confirmata', 'Receptionata', 'Anulata']],
                        ['name' => 'modalitate_livrare', 'label' => 'Modalitate livrare', 'type' => 'select', 'required' => true, 'options' => ['Curier', 'Transport propriu', 'Ridicare depozit']],
                        ['name' => 'moneda', 'label' => 'Moneda', 'type' => 'select', 'required' => true, 'options' => ['RON', 'EUR', 'USD']],
                    ],
                ],
                'linii-comanda' => [
                    'label' => 'Linii Comanda',
                    'icon' => 'fa-bars',
                    'table' => 'apr_linii_comanda',
                    'columns' => [
                        ['name' => 'comanda_id', 'label' => 'ID comanda', 'type' => 'bigint', 'required' => true, 'reference_table' => 'apr_comenzi'],
                        ['name' => 'cod_articol', 'label' => 'Cod articol', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_articol', 'label' => 'Denumire articol', 'type' => 'string', 'required' => true],
                        ['name' => 'cantitate', 'label' => 'Cantitate', 'type' => 'decimal', 'required' => true],
                        ['name' => 'pret_unitar', 'label' => 'Pret unitar', 'type' => 'decimal', 'required' => true],
                        ['name' => 'valoare_linie', 'label' => 'Valoare linie', 'type' => 'decimal'],
                        ['name' => 'unitate_masura', 'label' => 'Unitate masura', 'type' => 'select', 'required' => true, 'options' => ['buc', 'set', 'kg', 'litru']],
                    ],
                ],
                'receptii' => [
                    'label' => 'Receptii Marfa',
                    'icon' => 'fa-box-open',
                    'table' => 'apr_receptii',
                    'columns' => [
                        ['name' => 'comanda_id', 'label' => 'ID comanda', 'type' => 'bigint', 'required' => true, 'reference_table' => 'apr_comenzi'],
                        ['name' => 'cod_receptie', 'label' => 'Cod receptie', 'type' => 'string', 'required' => true],
                        ['name' => 'articol', 'label' => 'Articol', 'type' => 'string', 'required' => true],
                        ['name' => 'cantitate_receptionata', 'label' => 'Cantitate receptionata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'cantitate_acceptata', 'label' => 'Cantitate acceptata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_receptie', 'label' => 'Status receptie', 'type' => 'select', 'required' => true, 'options' => ['In verificare', 'Acceptata', 'Partial acceptata', 'Respinsa']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'facturi-furnizor' => [
                    'label' => 'Facturi Furnizor',
                    'icon' => 'fa-file-invoice',
                    'table' => 'apr_facturi_furnizor',
                    'columns' => [
                        ['name' => 'furnizor_id', 'label' => 'ID furnizor', 'type' => 'bigint', 'required' => true, 'reference_table' => 'apr_furnizori'],
                        ['name' => 'comanda_id', 'label' => 'ID comanda', 'type' => 'bigint', 'reference_table' => 'apr_comenzi'],
                        ['name' => 'cod_factura_furnizor', 'label' => 'Cod factura furnizor', 'type' => 'string', 'required' => true],
                        ['name' => 'valoare_factura', 'label' => 'Valoare factura', 'type' => 'decimal', 'required' => true],
                        ['name' => 'moneda', 'label' => 'Moneda', 'type' => 'select', 'required' => true, 'options' => ['RON', 'EUR', 'USD']],
                        ['name' => 'status_factura', 'label' => 'Status factura', 'type' => 'select', 'required' => true, 'options' => ['Primita', 'Validata', 'Platita', 'Blocata']],
                        ['name' => 'sold_factura', 'label' => 'Sold factura', 'type' => 'decimal'],
                    ],
                ],
                'plati-furnizor' => [
                    'label' => 'Plati Furnizor',
                    'icon' => 'fa-money-check-dollar',
                    'table' => 'apr_plati_furnizor',
                    'columns' => [
                        ['name' => 'factura_furnizor_id', 'label' => 'ID factura furnizor', 'type' => 'bigint', 'required' => true, 'reference_table' => 'apr_facturi_furnizor'],
                        ['name' => 'cod_plata', 'label' => 'Cod plata', 'type' => 'string', 'required' => true],
                        ['name' => 'suma_platita', 'label' => 'Suma platita', 'type' => 'decimal', 'required' => true],
                        ['name' => 'modalitate_plata', 'label' => 'Modalitate plata', 'type' => 'select', 'required' => true, 'options' => ['Transfer bancar', 'Card', 'Numerar']],
                        ['name' => 'status_plata', 'label' => 'Status plata', 'type' => 'select', 'required' => true, 'options' => ['Executata', 'In procesare', 'Respinsa']],
                        ['name' => 'referinta_banca', 'label' => 'Referinta banca', 'type' => 'string'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'stocuri' => [
                    'label' => 'Stocuri',
                    'icon' => 'fa-boxes-stacked',
                    'table' => 'apr_stocuri',
                    'columns' => [
                        ['name' => 'cod_articol', 'label' => 'Cod articol', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_articol', 'label' => 'Denumire articol', 'type' => 'string', 'required' => true],
                        ['name' => 'categorie_articol', 'label' => 'Categorie articol', 'type' => 'select', 'required' => true, 'options' => ['Scule motorizate', 'Echipamente agricole', 'Piese auto', 'Consumabile']],
                        ['name' => 'stoc_curent', 'label' => 'Stoc curent', 'type' => 'decimal', 'required' => true],
                        ['name' => 'stoc_minim', 'label' => 'Stoc minim', 'type' => 'decimal', 'required' => true],
                        ['name' => 'pret_mediu', 'label' => 'Pret mediu', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_stoc', 'label' => 'Status stoc', 'type' => 'select', 'required' => true, 'options' => ['Disponibil', 'Sub minim', 'Blocat']],
                    ],
                ],
            ],
        ],
        'mijloace-fixe' => [
            'label' => 'Mijloace Fixe',
            'icon' => 'fa-industry',
            'route_prefix' => 'mijloace-fixe',
            'table_prefix' => 'mfx_',
            'entities' => [
                'categorii' => [
                    'label' => 'Categorii',
                    'icon' => 'fa-tags',
                    'table' => 'mfx_categorii',
                    'columns' => [
                        ['name' => 'cod_categorie', 'label' => 'Cod categorie', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_categorie', 'label' => 'Denumire categorie', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_categorie', 'label' => 'Tip categorie', 'type' => 'select', 'required' => true, 'options' => ['Utilaj', 'Vehicul', 'Echipament service', 'Echipament IT']],
                        ['name' => 'durata_amortizare_luni', 'label' => 'Durata amortizare (luni)', 'type' => 'integer', 'required' => true],
                        ['name' => 'metoda_amortizare', 'label' => 'Metoda amortizare', 'type' => 'select', 'required' => true, 'options' => ['Liniara', 'Accelerata', 'Degresiva']],
                        ['name' => 'status_categorie', 'label' => 'Status categorie', 'type' => 'select', 'required' => true, 'options' => ['Activa', 'Inactiva']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'clasificari' => [
                    'label' => 'Clasificari Legale',
                    'icon' => 'fa-scale-balanced',
                    'table' => 'mfx_clasificari_legale',
                    'columns' => [
                        ['name' => 'cod_clasificare', 'label' => 'Cod clasificare', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_clasificare', 'label' => 'Denumire clasificare', 'type' => 'string', 'required' => true],
                        ['name' => 'grupa_legala', 'label' => 'Grupa legala', 'type' => 'string', 'required' => true],
                        ['name' => 'subgrupa_legala', 'label' => 'Subgrupa legala', 'type' => 'string'],
                        ['name' => 'cota_amortizare', 'label' => 'Cota amortizare (%)', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_clasificare', 'label' => 'Status clasificare', 'type' => 'select', 'required' => true, 'options' => ['Valida', 'Revizuita']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'mijloace' => [
                    'label' => 'Mijloace Fixe',
                    'icon' => 'fa-trailer',
                    'table' => 'mfx_mijloace',
                    'columns' => [
                        ['name' => 'categorie_id', 'label' => 'ID categorie', 'type' => 'bigint', 'required' => true, 'reference_table' => 'mfx_categorii'],
                        ['name' => 'clasificare_id', 'label' => 'ID clasificare', 'type' => 'bigint', 'required' => true, 'reference_table' => 'mfx_clasificari_legale'],
                        ['name' => 'cod_mijloc', 'label' => 'Cod mijloc fix', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_mijloc', 'label' => 'Denumire mijloc fix', 'type' => 'string', 'required' => true],
                        ['name' => 'valoare_intrare', 'label' => 'Valoare intrare', 'type' => 'decimal', 'required' => true],
                        ['name' => 'durata_utilizare_luni', 'label' => 'Durata utilizare (luni)', 'type' => 'integer', 'required' => true],
                        ['name' => 'status_mijloc', 'label' => 'Status mijloc', 'type' => 'select', 'required' => true, 'options' => ['In exploatare', 'In mentenanta', 'Casat']],
                    ],
                ],
                'amortizari' => [
                    'label' => 'Amortizari',
                    'icon' => 'fa-chart-pie',
                    'table' => 'mfx_amortizari',
                    'columns' => [
                        ['name' => 'mijloc_id', 'label' => 'ID mijloc fix', 'type' => 'bigint', 'required' => true, 'reference_table' => 'mfx_mijloace'],
                        ['name' => 'cod_amortizare', 'label' => 'Cod amortizare', 'type' => 'string', 'required' => true],
                        ['name' => 'valoare_amortizata', 'label' => 'Valoare amortizata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'amortizare_cumulata', 'label' => 'Amortizare cumulata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'valoare_ramasa', 'label' => 'Valoare ramasa', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_amortizare', 'label' => 'Status amortizare', 'type' => 'select', 'required' => true, 'options' => ['Calculata', 'Validata', 'Aprobata']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'reevaluari' => [
                    'label' => 'Reevaluari',
                    'icon' => 'fa-arrows-rotate',
                    'table' => 'mfx_reevaluari',
                    'columns' => [
                        ['name' => 'mijloc_id', 'label' => 'ID mijloc fix', 'type' => 'bigint', 'required' => true, 'reference_table' => 'mfx_mijloace'],
                        ['name' => 'cod_reevaluare', 'label' => 'Cod reevaluare', 'type' => 'string', 'required' => true],
                        ['name' => 'valoare_anterioara', 'label' => 'Valoare anterioara', 'type' => 'decimal', 'required' => true],
                        ['name' => 'valoare_noua', 'label' => 'Valoare noua', 'type' => 'decimal', 'required' => true],
                        ['name' => 'diferenta_valoare', 'label' => 'Diferenta valoare', 'type' => 'decimal'],
                        ['name' => 'status_reevaluare', 'label' => 'Status reevaluare', 'type' => 'select', 'required' => true, 'options' => ['Propusa', 'Aprobata', 'Aplicata']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'transferuri' => [
                    'label' => 'Transferuri',
                    'icon' => 'fa-right-left',
                    'table' => 'mfx_transferuri',
                    'columns' => [
                        ['name' => 'mijloc_id', 'label' => 'ID mijloc fix', 'type' => 'bigint', 'required' => true, 'reference_table' => 'mfx_mijloace'],
                        ['name' => 'cod_transfer', 'label' => 'Cod transfer', 'type' => 'string', 'required' => true],
                        ['name' => 'locatie_initiala', 'label' => 'Locatie initiala', 'type' => 'string', 'required' => true],
                        ['name' => 'locatie_noua', 'label' => 'Locatie noua', 'type' => 'string', 'required' => true],
                        ['name' => 'responsabil_transfer', 'label' => 'Responsabil transfer', 'type' => 'string', 'required' => true],
                        ['name' => 'status_transfer', 'label' => 'Status transfer', 'type' => 'select', 'required' => true, 'options' => ['Initiat', 'In curs', 'Finalizat']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'casari' => [
                    'label' => 'Casari',
                    'icon' => 'fa-trash-can',
                    'table' => 'mfx_casari',
                    'columns' => [
                        ['name' => 'mijloc_id', 'label' => 'ID mijloc fix', 'type' => 'bigint', 'required' => true, 'reference_table' => 'mfx_mijloace'],
                        ['name' => 'cod_casare', 'label' => 'Cod casare', 'type' => 'string', 'required' => true],
                        ['name' => 'motiv_casare', 'label' => 'Motiv casare', 'type' => 'string', 'required' => true],
                        ['name' => 'valoare_ramasa', 'label' => 'Valoare ramasa', 'type' => 'decimal', 'required' => true],
                        ['name' => 'valoare_recuperata', 'label' => 'Valoare recuperata', 'type' => 'decimal'],
                        ['name' => 'status_casare', 'label' => 'Status casare', 'type' => 'select', 'required' => true, 'options' => ['Propusa', 'Aprobata', 'Executata']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'mentenanta' => [
                    'label' => 'Mentenanta',
                    'icon' => 'fa-screwdriver-wrench',
                    'table' => 'mfx_mentenanta',
                    'columns' => [
                        ['name' => 'mijloc_id', 'label' => 'ID mijloc fix', 'type' => 'bigint', 'required' => true, 'reference_table' => 'mfx_mijloace'],
                        ['name' => 'cod_mentenanta', 'label' => 'Cod mentenanta', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_mentenanta', 'label' => 'Tip mentenanta', 'type' => 'select', 'required' => true, 'options' => ['Preventiva', 'Corectiva', 'Revizie']],
                        ['name' => 'furnizor_service', 'label' => 'Furnizor service', 'type' => 'string', 'required' => true],
                        ['name' => 'cost_mentenanta', 'label' => 'Cost mentenanta', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_mentenanta', 'label' => 'Status mentenanta', 'type' => 'select', 'required' => true, 'options' => ['Programata', 'Executata', 'Intarziata']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'documente' => [
                    'label' => 'Documente',
                    'icon' => 'fa-folder-tree',
                    'table' => 'mfx_documente',
                    'columns' => [
                        ['name' => 'mijloc_id', 'label' => 'ID mijloc fix', 'type' => 'bigint', 'required' => true, 'reference_table' => 'mfx_mijloace'],
                        ['name' => 'cod_document', 'label' => 'Cod document', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_document', 'label' => 'Tip document', 'type' => 'select', 'required' => true, 'options' => ['Factura', 'Proces verbal', 'Contract', 'Certificat']],
                        ['name' => 'numar_document', 'label' => 'Numar document', 'type' => 'string', 'required' => true],
                        ['name' => 'furnizor_emitent', 'label' => 'Furnizor emitent', 'type' => 'string'],
                        ['name' => 'valoare_document', 'label' => 'Valoare document', 'type' => 'decimal'],
                        ['name' => 'status_document', 'label' => 'Status document', 'type' => 'select', 'required' => true, 'options' => ['Valid', 'Expirat', 'Revizuit']],
                    ],
                ],
            ],
        ],
        'contabilitate' => [
            'label' => 'Contabilitate',
            'icon' => 'fa-calculator',
            'route_prefix' => 'contabilitate',
            'table_prefix' => 'cnt_',
            'entities' => [
                'plan-conturi' => [
                    'label' => 'Plan de Conturi',
                    'icon' => 'fa-book',
                    'table' => 'cnt_plan_conturi',
                    'columns' => [
                        ['name' => 'cod_cont', 'label' => 'Cod cont', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_cont', 'label' => 'Denumire cont', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_cont', 'label' => 'Tip cont', 'type' => 'select', 'required' => true, 'options' => ['Activ', 'Pasiv', 'Venit', 'Cheltuiala']],
                        ['name' => 'categorie_cont', 'label' => 'Categorie cont', 'type' => 'string', 'required' => true],
                        ['name' => 'nivel_cont', 'label' => 'Nivel cont', 'type' => 'integer', 'required' => true],
                        ['name' => 'status_cont', 'label' => 'Status cont', 'type' => 'select', 'required' => true, 'options' => ['Activ', 'Inactiv']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'jurnale' => [
                    'label' => 'Jurnale Contabile',
                    'icon' => 'fa-book-open',
                    'table' => 'cnt_jurnale',
                    'columns' => [
                        ['name' => 'cod_jurnal', 'label' => 'Cod jurnal', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_jurnal', 'label' => 'Denumire jurnal', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_jurnal', 'label' => 'Tip jurnal', 'type' => 'select', 'required' => true, 'options' => ['Vanzari', 'Cumparari', 'Casa', 'Banca', 'Diverse']],
                        ['name' => 'status_jurnal', 'label' => 'Status jurnal', 'type' => 'select', 'required' => true, 'options' => ['Deschis', 'Verificat', 'Inchis']],
                        ['name' => 'total_debit', 'label' => 'Total debit', 'type' => 'decimal', 'required' => true],
                        ['name' => 'total_credit', 'label' => 'Total credit', 'type' => 'decimal', 'required' => true],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'note-contabile' => [
                    'label' => 'Note Contabile',
                    'icon' => 'fa-note-sticky',
                    'table' => 'cnt_note_contabile',
                    'columns' => [
                        ['name' => 'jurnal_id', 'label' => 'ID jurnal', 'type' => 'bigint', 'required' => true, 'reference_table' => 'cnt_jurnale'],
                        ['name' => 'cod_nota', 'label' => 'Cod nota', 'type' => 'string', 'required' => true],
                        ['name' => 'explicatie_nota', 'label' => 'Explicatie nota', 'type' => 'string', 'required' => true],
                        ['name' => 'suma_debit', 'label' => 'Suma debit', 'type' => 'decimal', 'required' => true],
                        ['name' => 'suma_credit', 'label' => 'Suma credit', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_nota', 'label' => 'Status nota', 'type' => 'select', 'required' => true, 'options' => ['Inregistrata', 'Verificata', 'Corectata']],
                        ['name' => 'cont_corespondent', 'label' => 'Cont corespondent', 'type' => 'string'],
                    ],
                ],
                'centre-cost' => [
                    'label' => 'Centre de Cost',
                    'icon' => 'fa-bullseye',
                    'table' => 'cnt_centre_cost',
                    'columns' => [
                        ['name' => 'cod_centru', 'label' => 'Cod centru cost', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_centru', 'label' => 'Denumire centru cost', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_centru', 'label' => 'Tip centru cost', 'type' => 'select', 'required' => true, 'options' => ['Vanzari', 'Service', 'Logistica', 'Administrativ']],
                        ['name' => 'manager_centru', 'label' => 'Manager centru', 'type' => 'string', 'required' => true],
                        ['name' => 'buget_alocat', 'label' => 'Buget alocat', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_centru', 'label' => 'Status centru', 'type' => 'select', 'required' => true, 'options' => ['Activ', 'Inactiv']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'bugete' => [
                    'label' => 'Bugete Financiare',
                    'icon' => 'fa-wallet',
                    'table' => 'cnt_bugete',
                    'columns' => [
                        ['name' => 'centru_cost_id', 'label' => 'ID centru cost', 'type' => 'bigint', 'required' => true, 'reference_table' => 'cnt_centre_cost'],
                        ['name' => 'cod_buget', 'label' => 'Cod buget', 'type' => 'string', 'required' => true],
                        ['name' => 'categorie_buget', 'label' => 'Categorie buget', 'type' => 'select', 'required' => true, 'options' => ['Operational', 'Investitii', 'Mentenanta', 'Marketing']],
                        ['name' => 'valoare_planificata', 'label' => 'Valoare planificata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'valoare_consumata', 'label' => 'Valoare consumata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'valoare_disponibila', 'label' => 'Valoare disponibila', 'type' => 'decimal'],
                        ['name' => 'status_buget', 'label' => 'Status buget', 'type' => 'select', 'required' => true, 'options' => ['Deschis', 'Monitorizat', 'Inchis']],
                    ],
                ],
                'creante' => [
                    'label' => 'Creante',
                    'icon' => 'fa-hand-holding-dollar',
                    'table' => 'cnt_creante',
                    'columns' => [
                        ['name' => 'client_id', 'label' => 'ID client', 'type' => 'bigint', 'required' => true, 'reference_table' => 'ctc_clienti'],
                        ['name' => 'cod_creanta', 'label' => 'Cod creanta', 'type' => 'string', 'required' => true],
                        ['name' => 'suma_creanta', 'label' => 'Suma creanta', 'type' => 'decimal', 'required' => true],
                        ['name' => 'suma_incasata', 'label' => 'Suma incasata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'sold_creanta', 'label' => 'Sold creanta', 'type' => 'decimal'],
                        ['name' => 'status_creanta', 'label' => 'Status creanta', 'type' => 'select', 'required' => true, 'options' => ['Deschisa', 'Partiala', 'Stinsa']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'datorii' => [
                    'label' => 'Datorii',
                    'icon' => 'fa-file-circle-minus',
                    'table' => 'cnt_datorii',
                    'columns' => [
                        ['name' => 'furnizor_id', 'label' => 'ID furnizor', 'type' => 'bigint', 'required' => true, 'reference_table' => 'apr_furnizori'],
                        ['name' => 'cod_datorie', 'label' => 'Cod datorie', 'type' => 'string', 'required' => true],
                        ['name' => 'suma_datorie', 'label' => 'Suma datorie', 'type' => 'decimal', 'required' => true],
                        ['name' => 'suma_platita', 'label' => 'Suma platita', 'type' => 'decimal', 'required' => true],
                        ['name' => 'sold_datorie', 'label' => 'Sold datorie', 'type' => 'decimal'],
                        ['name' => 'status_datorie', 'label' => 'Status datorie', 'type' => 'select', 'required' => true, 'options' => ['Deschisa', 'Partiala', 'Stinsa']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'plati' => [
                    'label' => 'Plati',
                    'icon' => 'fa-credit-card',
                    'table' => 'cnt_plati',
                    'columns' => [
                        ['name' => 'datorie_id', 'label' => 'ID datorie', 'type' => 'bigint', 'required' => true, 'reference_table' => 'cnt_datorii'],
                        ['name' => 'cod_plata', 'label' => 'Cod plata', 'type' => 'string', 'required' => true],
                        ['name' => 'suma_plata', 'label' => 'Suma plata', 'type' => 'decimal', 'required' => true],
                        ['name' => 'modalitate_plata', 'label' => 'Modalitate plata', 'type' => 'select', 'required' => true, 'options' => ['Transfer bancar', 'Card', 'Numerar']],
                        ['name' => 'status_plata', 'label' => 'Status plata', 'type' => 'select', 'required' => true, 'options' => ['Confirmata', 'In procesare', 'Respinsa']],
                        ['name' => 'referinta_plata', 'label' => 'Referinta plata', 'type' => 'string'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'incasari-financiare' => [
                    'label' => 'Incasari Financiare',
                    'icon' => 'fa-piggy-bank',
                    'table' => 'cnt_incasari_financiare',
                    'columns' => [
                        ['name' => 'creanta_id', 'label' => 'ID creanta', 'type' => 'bigint', 'required' => true, 'reference_table' => 'cnt_creante'],
                        ['name' => 'cod_incasare', 'label' => 'Cod incasare', 'type' => 'string', 'required' => true],
                        ['name' => 'suma_incasare', 'label' => 'Suma incasare', 'type' => 'decimal', 'required' => true],
                        ['name' => 'modalitate_incasare', 'label' => 'Modalitate incasare', 'type' => 'select', 'required' => true, 'options' => ['Transfer bancar', 'Card', 'Numerar']],
                        ['name' => 'status_incasare', 'label' => 'Status incasare', 'type' => 'select', 'required' => true, 'options' => ['Confirmata', 'In procesare', 'Respinsa']],
                        ['name' => 'referinta_incasare', 'label' => 'Referinta incasare', 'type' => 'string'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
            ],
        ],
        'raportare' => [
            'label' => 'Raportare si Control',
            'icon' => 'fa-chart-column',
            'route_prefix' => 'raportare',
            'table_prefix' => 'rpt_',
            'entities' => [
                'kpi-definitii' => [
                    'label' => 'KPI Definitii',
                    'icon' => 'fa-compass-drafting',
                    'table' => 'rpt_kpi_definitii',
                    'columns' => [
                        ['name' => 'cod_kpi', 'label' => 'Cod KPI', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_kpi', 'label' => 'Denumire KPI', 'type' => 'string', 'required' => true],
                        ['name' => 'modul_sursa', 'label' => 'Modul sursa', 'type' => 'select', 'required' => true, 'options' => ['Proiecte', 'Contracte Client', 'Aprovizionare', 'Mijloace Fixe', 'Contabilitate', 'Raportare']],
                        ['name' => 'unitate_masura', 'label' => 'Unitate masura', 'type' => 'string', 'required' => true],
                        ['name' => 'formula_calcul', 'label' => 'Formula calcul', 'type' => 'text', 'required' => true],
                        ['name' => 'tinta_kpi', 'label' => 'Tinta KPI', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_kpi', 'label' => 'Status KPI', 'type' => 'select', 'required' => true, 'options' => ['Activ', 'Arhivat']],
                    ],
                ],
                'kpi-valori' => [
                    'label' => 'KPI Valori',
                    'icon' => 'fa-square-poll-vertical',
                    'table' => 'rpt_kpi_valori',
                    'columns' => [
                        ['name' => 'kpi_id', 'label' => 'ID KPI', 'type' => 'bigint', 'required' => true, 'reference_table' => 'rpt_kpi_definitii'],
                        ['name' => 'cod_inregistrare', 'label' => 'Cod inregistrare', 'type' => 'string', 'required' => true],
                        ['name' => 'valoare_kpi', 'label' => 'Valoare KPI', 'type' => 'decimal', 'required' => true],
                        ['name' => 'prag_alerta', 'label' => 'Prag alerta', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_kpi', 'label' => 'Status KPI', 'type' => 'select', 'required' => true, 'options' => ['Normal', 'Atentie', 'Critic']],
                        ['name' => 'scor_performanta', 'label' => 'Scor performanta', 'type' => 'decimal'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'rapoarte-standard' => [
                    'label' => 'Rapoarte Standard',
                    'icon' => 'fa-file-lines',
                    'table' => 'rpt_rapoarte_standard',
                    'columns' => [
                        ['name' => 'cod_raport', 'label' => 'Cod raport', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_raport', 'label' => 'Denumire raport', 'type' => 'string', 'required' => true],
                        ['name' => 'categorie_raport', 'label' => 'Categorie raport', 'type' => 'select', 'required' => true, 'options' => ['Operational', 'Financiar', 'Comercial', 'Audit']],
                        ['name' => 'format_raport', 'label' => 'Format raport', 'type' => 'select', 'required' => true, 'options' => ['PDF', 'Excel', 'HTML']],
                        ['name' => 'status_raport', 'label' => 'Status raport', 'type' => 'select', 'required' => true, 'options' => ['Activ', 'Revizie', 'Arhivat']],
                        ['name' => 'frecventa', 'label' => 'Frecventa', 'type' => 'string', 'required' => true],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'performanta-procese' => [
                    'label' => 'Performanta Procese',
                    'icon' => 'fa-gears',
                    'table' => 'rpt_performanta_procese',
                    'columns' => [
                        ['name' => 'cod_proces', 'label' => 'Cod proces', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_proces', 'label' => 'Denumire proces', 'type' => 'string', 'required' => true],
                        ['name' => 'eficienta_proces', 'label' => 'Eficienta proces (%)', 'type' => 'decimal', 'required' => true],
                        ['name' => 'cost_proces', 'label' => 'Cost proces', 'type' => 'decimal', 'required' => true],
                        ['name' => 'nivel_calitate', 'label' => 'Nivel calitate (%)', 'type' => 'decimal', 'required' => true],
                        ['name' => 'status_proces', 'label' => 'Status proces', 'type' => 'select', 'required' => true, 'options' => ['In tinta', 'Sub tinta', 'Critic']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'controale-interne' => [
                    'label' => 'Controale Interne',
                    'icon' => 'fa-shield-halved',
                    'table' => 'rpt_controale_interne',
                    'columns' => [
                        ['name' => 'cod_control', 'label' => 'Cod control', 'type' => 'string', 'required' => true],
                        ['name' => 'denumire_control', 'label' => 'Denumire control', 'type' => 'string', 'required' => true],
                        ['name' => 'responsabil_control', 'label' => 'Responsabil control', 'type' => 'string', 'required' => true],
                        ['name' => 'nivel_risc', 'label' => 'Nivel risc', 'type' => 'select', 'required' => true, 'options' => ['Scazut', 'Mediu', 'Ridicat']],
                        ['name' => 'status_control', 'label' => 'Status control', 'type' => 'select', 'required' => true, 'options' => ['Activ', 'In revizie', 'Suspendat']],
                        ['name' => 'scor_control', 'label' => 'Scor control', 'type' => 'decimal'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'neconformitati' => [
                    'label' => 'Neconformitati',
                    'icon' => 'fa-triangle-exclamation',
                    'table' => 'rpt_neconformitati',
                    'columns' => [
                        ['name' => 'cod_neconformitate', 'label' => 'Cod neconformitate', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_neconformitate', 'label' => 'Tip neconformitate', 'type' => 'string', 'required' => true],
                        ['name' => 'descriere_neconformitate', 'label' => 'Descriere neconformitate', 'type' => 'string', 'required' => true],
                        ['name' => 'severitate', 'label' => 'Severitate', 'type' => 'select', 'required' => true, 'options' => ['Minora', 'Majora', 'Critica']],
                        ['name' => 'status_neconformitate', 'label' => 'Status neconformitate', 'type' => 'select', 'required' => true, 'options' => ['Noua', 'In analiza', 'Rezolvata']],
                        ['name' => 'impact_financiar', 'label' => 'Impact financiar', 'type' => 'decimal'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'actiuni-corective' => [
                    'label' => 'Actiuni Corective',
                    'icon' => 'fa-screwdriver',
                    'table' => 'rpt_actiuni_corective',
                    'columns' => [
                        ['name' => 'neconformitate_id', 'label' => 'ID neconformitate', 'type' => 'bigint', 'required' => true, 'reference_table' => 'rpt_neconformitati'],
                        ['name' => 'cod_actiune', 'label' => 'Cod actiune', 'type' => 'string', 'required' => true],
                        ['name' => 'descriere_actiune', 'label' => 'Descriere actiune', 'type' => 'string', 'required' => true],
                        ['name' => 'responsabil_actiune', 'label' => 'Responsabil actiune', 'type' => 'string', 'required' => true],
                        ['name' => 'cost_actiune', 'label' => 'Cost actiune', 'type' => 'decimal'],
                        ['name' => 'status_actiune', 'label' => 'Status actiune', 'type' => 'select', 'required' => true, 'options' => ['Planificata', 'In curs', 'Finalizata']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'audituri' => [
                    'label' => 'Audituri',
                    'icon' => 'fa-magnifying-glass-chart',
                    'table' => 'rpt_audituri',
                    'columns' => [
                        ['name' => 'cod_audit', 'label' => 'Cod audit', 'type' => 'string', 'required' => true],
                        ['name' => 'tip_audit', 'label' => 'Tip audit', 'type' => 'select', 'required' => true, 'options' => ['Intern', 'Extern', 'Conformitate']],
                        ['name' => 'auditor', 'label' => 'Auditor', 'type' => 'string', 'required' => true],
                        ['name' => 'scor_audit', 'label' => 'Scor audit', 'type' => 'decimal'],
                        ['name' => 'status_audit', 'label' => 'Status audit', 'type' => 'select', 'required' => true, 'options' => ['Programat', 'In curs', 'Finalizat']],
                        ['name' => 'recomandari', 'label' => 'Recomandari', 'type' => 'text'],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
                'rezultate-integrate' => [
                    'label' => 'Rezultate Integrate',
                    'icon' => 'fa-square-poll-horizontal',
                    'table' => 'rpt_rezultate_integrate',
                    'columns' => [
                        ['name' => 'cod_rezultat', 'label' => 'Cod rezultat', 'type' => 'string', 'required' => true],
                        ['name' => 'modul_analizat', 'label' => 'Modul analizat', 'type' => 'select', 'required' => true, 'options' => ['Proiecte', 'Contracte Client', 'Aprovizionare', 'Mijloace Fixe', 'Contabilitate', 'Raportare']],
                        ['name' => 'indicator_cheie', 'label' => 'Indicator cheie', 'type' => 'string', 'required' => true],
                        ['name' => 'valoare_indicator', 'label' => 'Valoare indicator', 'type' => 'decimal', 'required' => true],
                        ['name' => 'nivel_performanta', 'label' => 'Nivel performanta', 'type' => 'select', 'required' => true, 'options' => ['Scazut', 'Mediu', 'Ridicat']],
                        ['name' => 'status_rezultat', 'label' => 'Status rezultat', 'type' => 'select', 'required' => true, 'options' => ['Validat', 'In verificare', 'Respins']],
                        ['name' => 'observatii', 'label' => 'Observatii', 'type' => 'text'],
                    ],
                ],
            ],
        ],
    ],
];
